name = "www-hexstreamsoft-com"

pages_build_output_dir = "./public"
send_metrics = true

compatibility_date = "2024-05-13"

services = [
  { binding = "R2", service = "r2_service" }
]

[limits]
cpu_ms = 10
